export const DATAS = [
  {
    id: 1,
    name: "Hon. Kingsley Ogundu Chinda",
    position: "Minority Leader",
    party: "PDP",
    constituency: "Obio/Akpor Federal Constituency",
    img: "https://example.com/candidate1.jpg",
  },
  {
    id: 2,
    name: "Hon. Ali Isah",
    position: "Minority Whip",
    party: "PDP",
    constituency: "Balanga/Billiri Federal Constituency  ",
    img: "https://example.com/candidate2.jpg",
  },
  {
    id: 3,
    name: "Hon. Aliyu Sani Madaki",
    position: "Deputy Minority Leader",
    party: "NNPP",
    constituency: "Dala Federal Constituency",
    img: "https://example.com/candidate3.jpg",
  },
  {
    id: 4,
    name: "Rt. Hon. George Ibezim Ozodinobi",
    position: "Member",
    party: "LP",
    constituency: "Njikoka/Dunukofia/Anaocha Federal Constituency",
    img: "https://example.com/candidate4.jpg",
  },
  {
    id: 5,
    name: "Hon. Fred Yetiemone Agbedi",
    position: "Member",
    party: "PDP",
    constituency: "Sagbama Ekeremor Federal Constituency",
    img: "https://example.com/candidate5.jpg",
  },
  {
    id: 6,
    name: "Hon. Gaza J. Gbefwi",
    position: "Position 5",
    party: "SDP",
    constituency: "Karu/Keffi/Kokona Federal Constituency",
    img: "https://example.com/candidate6.jpg",
  },
  {
    id: 7,
    name: "Hon. Garba Ibrahim Muhammad",
    position: "Member",
    party: "NNPP",
    constituency: "Gwale/Kano Federal Constituency",
    img: "https://example.com/candidate7.jpg",
  },
  {
    id: 8,
    name: "Hon. Fom Dalyop Chollom",
    position: "Member",
    party: "LP",
    constituency: "Barkin-Ladi/Riyom Federal Constituency",
    img: "https://example.com/candidate8.jpg",
  },
  {
    id: 9,
    name: "Hon. Godwin Offiono",
    position: "Member",
    party: "PDP",
    constituency: "Ogoja/Yala Federal Constituency ",
    img: "https://example.com/candidate9.jpg",
  },
  {
    id: 10,
    name: "Ajang Alfred Iliya",
    position: "Member",
    party: "LP",
    constituency: "Jos South/Jos East Federal",
    img: "https://example.com/candidate10.jpg",
  },
  {
    id: 11,
    name: "Hon. Abass A. Adigun",
    position: "Member",
    party: "PDP",
    constituency: "Ibadan North east/South East Federal Constituency",
    img: "https://example.com/candidate11.jpg",
  },
  {
    id: 12,
    name: "Hon. Abdullahi El-Rashed",
    position: "Member",
    party: "PDP",
    constituency: "Dukku/Nafada Federal Constituency ",
    img: "https://example.com/candidate12.jpg",
  },
  {
    id: 13,
    name: "Hon. Abdullahi Sani Rogo",
    position: "Member",
    party: "NNPP",
    constituency: "Karaye/Rogo Federal Constituency ",
    img: "https://example.com/candidate13.jpg",
  },
  {
    id: 14,
    name: "Hon. Abdulmaleek A. Danda",
    position: "Member",
    party: "PDP",
    constituency: "Adavi/Okehi Federal Constituency",
    img: "https://example.com/candidate14.jpg",
  },
  {
    id: 15,
    name: "Hon. Abubakar Abdul Buba",
    position: "Member",
    party: "PDP",
    constituency: "Chanchaga Federal Constituency",
    img: "https://example.com/candidate15.jpg",
  },
  {
    id: 16,
    name: "Hon. Adamu Tanko",
    position: "Member",
    party: "PDP",
    constituency: "Suleja/Gurara Federal Constituency",
    img: "https://example.com/candidate16.jpg",
  },
  {
    id: 17,
    name: "Hon. Adewale M. Adebanjo",
    position: "Member",
    party: "PDP",
    constituency: "Irepodun, Orolu, Olorunda, Osogbo Federal Constituency",
    img: "https://example.com/candidate17.jpg",
  },
  {
    id: 18,
    name: "Hon. Akiba Bassey Ekpenyong",
    position: "Member",
    party: "LP",
    constituency: "Calabar Municipal/Odukpani Federal Constituency",
    img: "https://example.com/candidate11.jpg",
  },
  {
    id: 19,
    name: "Hon. Akingbaso Olarenwaj",
    position: "Member",
    party: "PDP",
    constituency: "Idanre/Ifedore Federal Constituency",
    img: "https://example.com/candidate11.jpg",
  },
  {
    id: 20,
    name: "Hon. Aliyu Aminu Garu",
    position: "Member",
    party: "PDP",
    constituency: "Bauchi Federal Constituency ",
    img: "https://example.com/candidate12.jpg",
  },
  {
    id: 21,
    name: "Hon. Aliyu Bappa Misau",
    position: "Member",
    party: "PDP",
    constituency: "Misau/Dambam Federal Constituency",
    img: "https://example.com/candidate13.jpg",
  },
  {
    id: 22,
    name: "Hon. Aliyu Mustapha Abdullahi",
    position: "Member",
    party: "PDP",
    constituency: "Ikara/Kursau Federal Constituency ",
    img: "https://example.com/candidate14.jpg",
  },
  {
    id: 23,
    name: "Hon. Amobi Ogar",
    position: "Member",
    party: "LP",
    constituency: "Isiukwuato/Umunneochi Federal Constituency",
    img: "https://example.com/candidate15.jpg",
  },
  {
    id: 24,
    name: "Hon. Amos Gwamna Magaji",
    position: "Member",
    party: "PDP",
    constituency: "Jaba/Zangon Kataf Federal Constituency",
    img: "https://example.com/candidate16.jpg",
  },
  {
    id: 25,
    name: "Hon. Aniekwe Peter Udogalanya",
    position: "Member",
    party: "LP",
    constituency: "Anambra East/West Federal Constituency",
    img: "https://example.com/candidate17.jpg",
  },
  {
    id: 26,
    name: "Hon. Attorney. Mathew Nwogu",
    position: "Member",
    party: "LP",
    constituency: "Aboh Mbaise/Ngor-Okpala Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 27,
    name: "Hon. Barr Benedict Etanabene",
    position: "Member",
    party: "LP",
    constituency: "Okpe/Sapele/Uvwie Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 28,
    name: "Hon. Barr. Okey-Joe Onuakalusi",
    position: "Member",
    party: "LP",
    constituency: "Oshodi/Isolo 2 Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 29,
    name: "Hon. Barr. Rabiu Yusuf",
    position: "Member",
    party: "NNPP",
    constituency: "Sumaila/Takai FedConstituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 30,
    name: "Hon. Bashiru Usman Gorau",
    position: "Member",
    party: "PDP",
    constituency: "Goronyo/Gada Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 31,
    name: "Hon. Dahiru Madaki",
    position: "Member",
    party: "PDP",
    constituency: "ADutse, Kiyawa Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 32,
    name: "Hon. Daniel Amos",
    position: "Member",
    party: "PDP",
    constituency: "Jamaa/Sanga Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 33,
    name: "Hon. Dr. Martins Oke",
    position: "Member",
    party: "PDP",
    constituency: "Igbo Etiti/Uzo Uwani Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 34,
    name: "Hon. Emeka Idu Godwin Obiajulu",
    position: "Member",
    party: "LP",
    constituency: " Onitsha North/South Federal constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 35,
    name: "Hon. Enenimiete Ebikake",
    position: "Member",
    party: "PDP",
    constituency: "Brass/Nembe Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 36,
    name: "Hon. Engr Sagir Ibrahim Koki",
    position: "Member",
    party: "NNPP",
    constituency: "AKano Municipal Federal",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 37,
    name: "Hon. Engr. Rodney E. Ambaiowei",
    position: "Member",
    party: "PDP",
    constituency: "Southern Ijaw Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 38,
    name: "Hon. Salisu Majigiri",
    position: "Member",
    party: "PDP",
    constituency: "Marshi/Dutsi Federal",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 39,
    name: "Hon. Sani Ibrahim Tanko",
    position: "Member",
    party: "PDP",
    constituency: "Shira/Giade Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 40,
    name: "Hon. Thaddeaus Attah",
    position: "Member",
    party: "LP",
    constituency: "Eti Osa Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 41,
    name: "Hon. Tijjani Abdulkadir Jobe",
    position: "Member",
    party: "NNPP",
    constituency: "D,Tofa/Tofa/Rimin-Gado Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 42,
    name: "Hon. Tochukwu Okere",
    position: "Member",
    party: "LP",
    constituency: "AOwerri north/West and Municipal Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 43,
    name: "Hon. Uduak Alphonsus Ududoh",
    position: "Member",
    party: "PDP",
    constituency: "Ikot Abasi/Mkpat Enin/Eastern Obolo Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 44,
    name: "Hon. Umeha S. Cyriacus",
    position: "Member",
    party: "LP",
    constituency: " Ezeagu/Udi Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 45,
    name: "Hon. Umezuruike Manuchim",
    position: "Member",
    party: "LP",
    constituency: "Port Harcourt 1 Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 46,
    name: "Hon. Yusuf Shittu Galambi",
    position: "Member",
    party: "NNPP",
    constituency: "Gwaram Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 47,
    name: "Hon.(Dr) Sulaiman Abubakar Gumi FNSE",
    position: "Member",
    party: "PDP",
    constituency: "Gummi/Bukkuyum Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 48,
    name: "Hon. Ibe Okwara Osonwa",
    position: "Member",
    party: "LP",
    constituency: "Arochukwu/Ohafia FederalConstituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 49,
    name: "Hon. James Shuaibu Barka",
    position: "Member",
    party: "PDP",
    constituency: "Gombi/Hong FederalConstituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 50,
    name: "Hon. Joshua A. Gana",
    position: "Member",
    party: "PDP",
    constituency: "Lavun/Mokwa/Edati Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 51,
    name: "Hon. Kobis Ari Thimnu",
    position: "Member",
    party: "PDP",
    constituency: "AGuyuk/Shelleng Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 52,
    name: "Hon. Mark C. Obetta",
    position: "Member",
    party: "LP",
    constituency: "Nsukka/Igbo-Eze South Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 53,
    name: "Hon. Mohammed Audi",
    position: "Member",
    party: "PDP",
    constituency: "Ardo K/Lau/Karim Lamido Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 54,
    name: "Hon. Mohammed Dan Abba Shehu",
    position: "Member",
    party: "PDP",
    constituency: "Zaki Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 55,
    name: "Hon. Mohammed Garba Chiroma",
    position: "Member",
    party: "NNPP",
    constituency: "AGezawa/Gabasawa Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 56,
    name: "Hon. Munachim I. Alozie",
    position: "Member",
    party: "LP",
    constituency: "Obingwa/Ugwunagbo/Osisioma Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 57,
    name: "Hon. Nnolim Nnaji",
    position: "Member",
    party: "PDP",
    constituency: "Nkanu East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 58,
    name: "Hon. Nweke Felix",
    position: "Member",
    party: "PDP",
    constituency: "Eleme/Oyigbo/Tai Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 59,
    name: "Hon. Obed Shehu",
    position: "Member",
    party: "PDP",
    constituency: "Kaltungo/Shongon Federal Constituency ",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 60,
    name: "Hon. Obi Aguocha",
    position: "Member",
    party: "LP",
    constituency: "Ikwuano Umuahia north/Umuahai South Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 61,
    name: "Hon. Obordor Mitema",
    position: "Member",
    party: "PDP",
    constituency: "Ogbia Federal Constituency ",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 62,
    name: "Hon. Okpolupm Ikpong Etteh",
    position: "Member",
    party: "PDP",
    constituency: "Eket/Onna/Esit Eket/Ibeno Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
  {
    id: 63,
    name: "Hon. Omirin Olusanya",
    position: "Member",
    party: "PDP",
    constituency: "Atakumosa East/West/Ilesa East/West Federal Constituency",
    img: "https://example.com/candidate18.jpg",
  },
];
