export const DATAS = [
  {
    id: 1,
    name: "Candidate 1",
    position: "Position 73",
    party: "ADC",
    constituency: "Constituency 29",
  },
  {
    id: 2,
    name: "Candidate 2",
    position: "Position 92",
    party: "LP",
    constituency: "Constituency 14",
  },
  {
    id: 3,
    name: "Candidate 3",
    position: "Position 58",
    party: "NNPP",
    constituency: "Constituency 44",
  },
  {
    id: 4,
    name: "Candidate 4",
    position: "Position 3",
    party: "PDP",
    constituency: "Constituency 18",
  },
  {
    id: 5,
    name: "Candidate 5",
    position: "Position 29",
    party: "SDP",
    constituency: "Constituency 20",
  },
  {
    id: 6,
    name: "Candidate 6",
    position: "Position 5",
    party: "PDP",
    constituency: "Constituency 23",
  },
  {
    id: 7,
    name: "Candidate 7",
    position: "Position 35",
    party: "LP",
    constituency: "Constituency 2",
  },
  {
    id: 8,
    name: "Candidate 8",
    position: "Position 83",
    party: "NNPP",
    constituency: "Constituency 30",
  },
  {
    id: 9,
    name: "Candidate 9",
    position: "Position 60",
    party: "ADC",
    constituency: "Constituency 19",
  },
  {
    id: 10,
    name: "Candidate 10",
    position: "Position 71",
    party: "LP",
    constituency: "Constituency 21",
  },
  {
    id: 11,
    name: "Candidate 11",
    position: "Position 79",
    party: "SDP",
    constituency: "Constituency 43",
  },
  {
    id: 12,
    name: "Candidate 12",
    position: "Position 17",
    party: "NNPP",
    constituency: "Constituency 8",
  },
  {
    id: 13,
    name: "Candidate 13",
    position: "Position 76",
    party: "PDP",
    constituency: "Constituency 41",
  },
  {
    id: 14,
    name: "Candidate 14",
    position: "Position 28",
    party: "ADC",
    constituency: "Constituency 34",
  },
  {
    id: 15,
    name: "Candidate 15",
    position: "Position 13",
    party: "PDP",
    constituency: "Constituency 49",
  },
  {
    id: 16,
    name: "Candidate 16",
    position: "Position 63",
    party: "NNPP",
    constituency: "Constituency 27",
  },
  {
    id: 17,
    name: "Candidate 17",
    position: "Position 44",
    party: "SDP",
    constituency: "Constituency 22",
  },
  {
    id: 18,
    name: "Candidate 18",
    position: "Position 51",
    party: "LP",
    constituency: "Constituency 11",
  },
  {
    id: 19,
    name: "Candidate 19",
    position: "Position 94",
    party: "ADC",
    constituency: "Constituency 6",
  },
  {
    id: 20,
    name: "Candidate 20",
    position: "Position 11",
    party: "PDP",
    constituency: "Constituency 26",
  },
];
